branch-defaults:
  default:
    environment: hello-eb-dev-kevinv2
    group_suffix: null
global:
  application_name: hello-eb
  branch: null
  default_ec2_keyname: clavelucatic2
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
